[package]
name = "rust_bench"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["full"] }
reqwest = {version = "0.12", features = ["json", "gzip"]}
clap = {version = "4", features = ["derive"]}